
runtime: python39
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
entrypoint: gunicorn -b :$PORT mysite.wsgi
instance_class: F2
env_variables:
  DJANGO_SETTINGS_MODULE: "mysite.settings"
